/*
Brian Hodge
C00170400
CMPS 260
Programming Assignment : #7
Due Date: 04/23/2019
Program Description: the program uses file I/O & a scanner object to prompt the user to select which file to open and
retrieve data from to use for the rest of the program loop. The loop prompts the user with questions for the data until the
user decides to quit the program.

Certificate of Authenticity: I certify that the code of this project, other than that that was generated by IntelliJ or
provided by the instructor, is entirely my own work.
 */



package com.company;
import java.io.File;
import java.util.Scanner;
import java.util.ArrayList;

public class Main {

    public static void main(String[] args) {

        Scanner userInput = new Scanner(System.in);
        System.out.print("Enter city file path: ");
        String fileName = userInput.nextLine();
        File cityFile = new File(fileName);
        City city;

        try (Scanner cityInfo = new Scanner(cityFile)) {
            city = new City(cityInfo);
            System.out.println();
            System.out.println(city.getCityName());
            System.out.println(city.getStateName());
            System.out.println(city.getStateAbrev());
            System.out.println("Population: " + city.totalPop());
            System.out.println("Avg Lat:    " + city.avgLatitude());
            System.out.println("Avg Long:  " + city.avgLongitude());
            //System.out.println();

            File measures = new File("questions.txt");
            //Scanner ask = null;
            ArrayList<String> questions = new ArrayList<>();

            try (Scanner ask = new Scanner(measures)) {
                while (ask.hasNextLine()) {
                    questions.add(ask.nextLine());
                }
                System.out.println();
                String proceed;
                do {
                    int i;
                    for (i = 0; i < questions.size(); i++) {
                        System.out.println(i + 1 + ":" + questions.get(i));
                    }
                    System.out.print("Measure? ");
                    int measure = userInput.nextInt();
                    userInput.nextLine();
                    System.out.println();
                    System.out.print("avg value:      ");
                    System.out.printf("%.2f", + city.avgPercent(measure));
                    System.out.print("%");
                    System.out.println();
                    System.out.print("avg lower:      ");
                    System.out.printf("%2.2f", + city.avgLower(measure));
                    System.out.print("%");
                    System.out.println();
                    System.out.print("avg upper:      ");
                    System.out.printf("%2.2f", +city.avgUpper(measure));
                    System.out.print("%");
                    System.out.println();
                    System.out.print("Continue?  (Y/N) ");
                    proceed = userInput.nextLine();
                } while (proceed.equals("y"));
                userInput.close();
            } catch (Exception ex) {
                ex.printStackTrace();
                System.out.print("inner");
            }
            } catch (Exception ex) {
                ex.printStackTrace();
                System.out.print("outer");
            }

    }
}
